### ISSUE TITLE
Convert to WASM

### ISSUE THREAD

**Issue by nbittich** [madrobby/vapor.js#111]
Performance are terrible for a modern library. Please convert your code into web assembly.

**Comment by gionkunz** [comment]
I think its great that you provide your feedback. But given that the authors are so busy fixing all those bugs and replying to issues, don't you think it would be better if you at least try to implement this yourself and then do a PR?

**Comment by TheTechRobo** [comment]
...except they're not replying to issues

**Comment by nbittich** [comment]
https://github.com/madrobby/vapor.js/pull/112

**Comment by nbittich** [comment]
Not sure I've followed the correct coding guidelines. hopefully I'm using the same eslint configuration than the authors.

**Comment by TheTechRobo** [comment]
Yeah, looks like it.
