### ISSUE TITLE
Provide TypeScript definitions (aka d.ts file)

### ISSUE THREAD

**Issue by Oceanswave** [madrobby/vapor.js#82]
I find it way too hard to be productive with vapor.js when I'm using typescript. I spent hours staring at my screen with no sense of direction of where to go.

Could a typescript definition be provided?

That would be awesome.

Thanks.

**Comment by gionkunz** [comment]
Why use definitions when you can use the typescript port? Just include vapor.ts from the repository!

**Comment by Oceanswave** [comment]
Ah ha! I missed this somehow! Things will be so much better, thanks!!

Vapor is the best!
